### ISSUE TITLE
cudaGetDeviceCount error

### ISSUE THREAD

**Issue by pihalf** [aime-team/aime-ml-containers#6]
I created a new container with from: `aimehub/pytorch-2.0.0-cuda11.7` with `mlc-create`, however, upon running cuda-specific commands I get breaking errors:

```
[torch20] user@machine:/workspace$ python -c "import torch; print(torch.rand(5).cuda())"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Unexpected error from cudaGetDeviceCount(). Did you run some cuda functions before calling NumCudaDevices() that might have already set an error? Error 804: forward compatibility was attempted on non supported HW
```

GPUs are 3090s and show up as expected with the `nvidia-smi`-command. 

Accessing pytorch with cuda on my older images (i.e. `Pytorch-1.11.0`) works just as expected. Furthermore, I'm able to update torch to 2.0 using pip without breaking the environment. 

Going deeper, I tried to create fresh images and do the same command as above. To my surprise, I get the same `cuda` error across these torch images:

- `2.0.0`
- `1.13.1`
- `1.13.0`

But it *works* when installing from `aimehub/pytorch-1.12.1-cuda11.3` and versions that pre-date it, which seem to indicate something with the cuda drivers.  

Any suggestions?

**Comment by kinred** [comment]
This could be indeed a host NVIDIA driver issue. 

For CUDA 11.7 based containers the host NVIDIA driver has probably to be version 515 or newer.

Could you provide the output of following commands (execute outside of the container):

`apt list --installed | grep cuda-1`

and

 `apt list --installed | grep nvidia-driver`

**Comment by pihalf** [comment]
Here's the output from the commands:

```
user@machine:~$ apt list --installed | grep cuda-1
cuda-11-2/unknown,now 11.2.2-1 amd64 [installed]
```

```
user@machine:~$ apt list --installed | grep nvidia-driver
nvidia-driver-470/unknown,now 470.161.03-0ubuntu1 amd64 [installed,automatic]
```

**Comment by kinred** [comment]
Ok, thank you, the driver is indeed to old to run CUDA 11.7 based containers. To update the driver we would suggest following procedure:

Remove the old driver by:

```
sudo apt-get remove cuda-11-2
sudo apt-get autoremove
```

This should automatically remove all depended CUDA libraries and the NVIDIA driver.

A key update for the CUDA repo is probably required, as the old key is maybe outdated, to do so:

```
sudo apt-key del 7fa2af80
sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/3bf863cc.pub

wget -qO - https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub | sudo apt-key add -
```

Now the latest apt packages have to be fetched:

`sudo apt-get update
`
There should be no warnings that there is an outdated key for the NVIDIA repo.

Now a later CUDA version with compatible driver can be installed, we would suggest CUDA 11.7 for Ampere based GPUs. To do so execute:

`sudo apt-get install cuda-11-7
`

Maybe a reboot is required after the installation has finised so that the driver can initialize correctly.

**Comment by pihalf** [comment]
Ahh okay thanks! Somehow expected `apt-get update;apt-get upgrade` would take care of this. 

Will give it a shot and let you know how it goes. Cheers

Update: Tested and works exactly as expected. Thank you!
